### ISSUE TITLE
pip installation failed - No such file or directory: 'requires.txt' / 'requirements.txt'

### ISSUE THREAD

**Issue by snowinmars** [mikaelalafriz/lucid-sonic-dreams#10]
I can't install `lucidsonicdreams` package from `pip`. How can I fix this?

```
> python --version
Python 3.9.1
> pip --version
pip 21.0.1 from c:\users\snowinmars\appdata\local\programs\python\python39\lib\site-packages\pip (python 3.9)
```

```
> pip install lucidsonicdreams
Collecting lucidsonicdreams
  Using cached lucidsonicdreams-0.4.tar.gz (11 kB)
  Using cached lucidsonicdreams-0.3.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\snowinmars\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\snowinmars\\AppData\\Local\\Temp\\pip-install-ar6zwq56\\lucidsonicdreams_8fb841c67fb348edbc51308b18dbeca2\\setup.py'"'"'; __file__='"'"'C:\\Users\\snowinmars\\AppData\\Local\\Temp\\pip-install-ar6zwq56\\lucidsonicdreams_8fb841c67fb348edbc51308b18dbeca2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\snowinmars\AppData\Local\Temp\pip-pip-egg-info-kilt0z0t'
         cwd: C:\Users\snowinmars\AppData\Local\Temp\pip-install-ar6zwq56\lucidsonicdreams_8fb841c67fb348edbc51308b18dbeca2\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\snowinmars\AppData\Local\Temp\pip-install-ar6zwq56\lucidsonicdreams_8fb841c67fb348edbc51308b18dbeca2\setup.py", line 5, in <module>
        with open('requires.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requires.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d7/83/4a4d53f2fb26fdb1c99cb7f6bbcda0a09803961674a3704181d85d3332df/lucidsonicdreams-0.3.tar.gz#sha256=305452861e1fa9abc5233022d45b0793f0c5ac78ef1cd0a070c87ad7b90ac8d4 (from https://pypi.org/simple/lucidsonicdreams/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached lucidsonicdreams-0.2.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\snowinmars\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\snowinmars\\AppData\\Local\\Temp\\pip-install-ar6zwq56\\lucidsonicdreams_1c85822b96914a29ad39ce142eb5599d\\setup.py'"'"'; __file__='"'"'C:\\Users\\snowinmars\\AppData\\Local\\Temp\\pip-install-ar6zwq56\\lucidsonicdreams_1c85822b96914a29ad39ce142eb5599d\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\snowinmars\AppData\Local\Temp\pip-pip-egg-info-tjkvyr4h'
         cwd: C:\Users\snowinmars\AppData\Local\Temp\pip-install-ar6zwq56\lucidsonicdreams_1c85822b96914a29ad39ce142eb5599d\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\snowinmars\AppData\Local\Temp\pip-install-ar6zwq56\lucidsonicdreams_1c85822b96914a29ad39ce142eb5599d\setup.py", line 5, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/da/11/7023ff17dbe1c22a44e68d21733aba09377dc523420724d4fa1a2decc4c0/lucidsonicdreams-0.2.tar.gz#sha256=90c96ad446c4d12579737ba2b39476537dfbe42be8515e90294562191150e42e (from https://pypi.org/simple/lucidsonicdreams/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from lucidsonicdreams)
ERROR: No matching distribution found for tensorflow==1.15
```

**Comment by MaveCordes** [comment]
Try using Python 3.6 or 3.7. Worked for me
