### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by nmcilree** [mikaelalafriz/lucid-sonic-dreams#12]
Hi - I'm getting several errors when running pip install on python 3.6 or 3.7. This is running in a docker container on either

- python:3.6-slim-buster
- python:3.7-stretch
- python:3.6-stretch

pip install lucidsonicdreams

```
Collecting lucidsonicdreams
  Downloading lucidsonicdreams-0.4.tar.gz (11 kB)
  Downloading lucidsonicdreams-0.3.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-q39u62_m/lucidsonicdreams_bddf7121fc1345a79d2bef3fe71038ba/setup.py'"'"'; __file__='"'"'/tmp/pip-install-q39u62_m/lucidsonicdreams_bddf7121fc1345a79d2bef3fe71038ba/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-9maokkz4
         cwd: /tmp/pip-install-q39u62_m/lucidsonicdreams_bddf7121fc1345a79d2bef3fe71038ba/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-q39u62_m/lucidsonicdreams_bddf7121fc1345a79d2bef3fe71038ba/setup.py", line 5, in <module>
        with open('requires.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requires.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d7/83/4a4d53f2fb26fdb1c99cb7f6bbcda0a09803961674a3704181d85d3332df/lucidsonicdreams-0.3.tar.gz#sha256=305452861e1fa9abc5233022d45b0793f0c5ac78ef1cd0a070c87ad7b90ac8d4 (from https://pypi.org/simple/lucidsonicdreams/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading lucidsonicdreams-0.2.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-q39u62_m/lucidsonicdreams_875d03b894b34161a37add828ed8608c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-q39u62_m/lucidsonicdreams_875d03b894b34161a37add828ed8608c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-m2iwh0_d
         cwd: /tmp/pip-install-q39u62_m/lucidsonicdreams_875d03b894b34161a37add828ed8608c/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-q39u62_m/lucidsonicdreams_875d03b894b34161a37add828ed8608c/setup.py", line 5, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/da/11/7023ff17dbe1c22a44e68d21733aba09377dc523420724d4fa1a2decc4c0/lucidsonicdreams-0.2.tar.gz#sha256=90c96ad446c4d12579737ba2b39476537dfbe42be8515e90294562191150e42e (from https://pypi.org/simple/lucidsonicdreams/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from lucidsonicdreams)
ERROR: No matching distribution found for tensorflow==1.15
```

**Comment by hunterirving** [comment]
I'm having the same issue, were you able to find a fix for this, @nmcilree?

**Comment by hunterirving** [comment]
Nevermind - I was able to find a fix. For anyone else who encounters this issue, according to this stackoverflow question (https://stackoverflow.com/questions/48720833/could-not-find-a-version-that-satisfies-the-requirement-tensorflow), 

> 

    Tensorflow only supports the 64-bit version of Python

    Tensorflow only supports Python 3.5 to 3.8

For some reason, I had the 32-bit version of Python 3.6.8 installed.
After removing that and reinstalling the 64-bit version (I stayed on 3.6.8), I was able to progress.

**Comment by jsigler47** [comment]
Just a heads up I was able to get around this on a Macbook with [pyenv](https://www.chrisjmendez.com/2017/08/03/installing-multiple-versions-of-python-on-your-mac-using-homebrew/) and Python 3.7.2
