### ISSUE TITLE
Getting several install errors

### ISSUE THREAD

**Issue by robot-99** [mikaelalafriz/lucid-sonic-dreams#16]
ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\envs\3-D-Art\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] =
'"'"'C:\\Users\\booki\\AppData\\Local\\Temp\\pip-install-lb5p0zlt\\lucidsonicdreams_4a0aa72bc164402da4ee92560c52efdb\
\setup.py'"'"'; __file__='"'"'C:\\Users\\booki\\AppData\\Local\\Temp\\pip-install-lb5p0zlt\\lucidsonicdreams_4a0aa72b
c164402da4ee92560c52efdb\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'
"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\boo
ki\AppData\Local\Temp\pip-pip-egg-info-pjjiy2vy'
         cwd: C:\Users\booki\AppData\Local\Temp\pip-install-lb5p0zlt\lucidsonicdreams_4a0aa72bc164402da4ee92560c52efd
b\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\booki\AppData\Local\Temp\pip-install-lb5p0zlt\lucidsonicdreams_4a0aa72bc164402da4ee92560c52efdb\
setup.py", line 5, in <module>
        with open('requires.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requires.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d7/83/4a4d53f2fb26fdb1c99cb7f6bbcda0a09803961674a3704181d
85d3332df/lucidsonicdreams-0.3.tar.gz#sha256=305452861e1fa9abc5233022d45b0793f0c5ac78ef1cd0a070c87ad7b90ac8d4 (from h
ttps://pypi.org/simple/lucidsonicdreams/). Command errored out with exit status 1: python setup.py egg_info Check the
 logs for full command output.
  Using cached lucidsonicdreams-0.2.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\envs\3-D-Art\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] =
'"'"'C:\\Users\\booki\\AppData\\Local\\Temp\\pip-install-lb5p0zlt\\lucidsonicdreams_109d0e81245c40379f7f43e9aeed38c4\
\setup.py'"'"'; __file__='"'"'C:\\Users\\booki\\AppData\\Local\\Temp\\pip-install-lb5p0zlt\\lucidsonicdreams_109d0e81
245c40379f7f43e9aeed38c4\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'
"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\boo
ki\AppData\Local\Temp\pip-pip-egg-info-11crgkgc'
         cwd: C:\Users\booki\AppData\Local\Temp\pip-install-lb5p0zlt\lucidsonicdreams_109d0e81245c40379f7f43e9aeed38c
4\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\booki\AppData\Local\Temp\pip-install-lb5p0zlt\lucidsonicdreams_109d0e81245c40379f7f43e9aeed38c4\
setup.py", line 5, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------

**Comment by lucaconte** [comment]
same here, updated Arch Linux unable to install using 
`pip install` due to a similar error:
`FileNotFoundError: [Errno 2] No such file or directory: 'requires.txt'
`

**Comment by robot-99** [comment]
I believe it has to do with it working with tensorflow 1.15 breaking on python3. I tried to backwards install it with Anacondas using the earlier versions of python but ran into problems with tensorflow again :/

**Comment by sean-custer** [comment]
Have you tried looking into which version of Python you are using? Currently, this module is only supported on Python 3.6 and 3.7.

Also, as robot-99 mentioned, tensorflow has been throwing some weird issues relating to whether you are running in 32-bit or 64-bit. 

See: https://github.com/mikaelalafriz/lucid-sonic-dreams/issues/12#issuecomment-807927300
