### ISSUE TITLE
Error with GPU device  on hallucinate() on MacBook Pro

### ISSUE THREAD

**Issue by SalahEddin** [mikaelalafriz/lucid-sonic-dreams#21]
I get an exception on `hallicinate()`'s first frame with the following traceback

```
Hallucinating... 

  0%|                                                                                                     | 0/6356 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/{USER}/.pyenv/versions/3.7.8/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/Users/{USER}/.pyenv/versions/3.7.8/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/Users/{USER}/.pyenv/versions/3.7.8/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation G_mapping_1/_Run/G_mapping/latents_in: {{node G_mapping_1/_Run/G_mapping/latents_in}} was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0 ]. Make sure the device specification refers to a valid device. The requested device appears to be a GPU, but CUDA is not enabled.
         [[G_mapping_1/_Run/G_mapping/latents_in]]
```

Specs:
MacBook Pro 2019 - 10.15.7 - Radeon Pro 555X 4 GB - Intel UHD Graphics 630 1536 MB

**Comment by pim0223** [comment]
lol noob

**Comment by deltaRing** [comment]
You may need CUDA, but, CUDA is not supported to Radeon Pro 555X.
