### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Colliwomple** [mikaelalafriz/lucid-sonic-dreams#26]
Ubuntu 20.04 
I made a test.py put it in folder "lucidsonicdreams and execute it from there.
What i get is this:
`Lucid) xxxxx:~/lucid$ python test.py
WARNING:tensorflow:From /home/hades/anaconda3/envs/Lucid/lib/python3.7/site-packages/dnnlib/tflib/tfutil.py:34: The name tf.Dimension is deprecated. Please use tf.compat.v1.Dimension instead.

WARNING:tensorflow:From /home/hades/anaconda3/envs/Lucid/lib/python3.7/site-packages/dnnlib/tflib/tfutil.py:74: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/hades/anaconda3/envs/Lucid/lib/python3.7/site-packages/dnnlib/tflib/tfutil.py:128: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

Preparing style...
WARNING:tensorflow:From /home/hades/anaconda3/envs/Lucid/lib/python3.7/site-packages/dnnlib/tflib/tfutil.py:97: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

WARNING:tensorflow:From /home/hades/anaconda3/envs/Lucid/lib/python3.7/site-packages/dnnlib/tflib/tfutil.py:109: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

WARNING:tensorflow:From /home/hades/anaconda3/envs/Lucid/lib/python3.7/site-packages/dnnlib/tflib/tfutil.py:132: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

Downloading painting faces weights (This may take a while)...
Downloading...
From: https://drive.google.com/uc?id=1H-MYFZqngF1R0whm4bc3fEoX7VvOWaDl
To: /home/hades/lucid/painting faces.pkl
382MB [00:29, 13.1MB/s] 
Download complete
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    duration = 90)
  File "/home/hades/lucid/lucidsonicdreams/main.py", line 636, in hallucinate
    self.stylegan_init()
  File "/home/hades/lucid/lucidsonicdreams/main.py", line 126, in stylegan_init
    self.Gs = pickle.load(f)[2]
  File "/home/hades/anaconda3/envs/Lucid/lib/python3.7/site-packages/dnnlib/tflib/network.py", line 279, in __setstate__
    assert state["version"] in [2, 3]
AssertionError
`

Anyone know how to solve this ??

**UPDATE !!!!
For me the solution was:
Putting my script test.py and the wav/mp3 in the stylegan2 folder ! Now everything runs smooth without any errors**

Maybe this is helpful for you !

**Comment by deltaRing** [comment]
Oops, it seems that works for some pkl files but still remains errors.
