### ISSUE TITLE
TensorFlow pickle version too low

### ISSUE THREAD

**Issue by tracycam** [mikaelalafriz/lucid-sonic-dreams#31]
E:\aimv2\venv\Scripts\python.exe E:/aimv2/main.py
Preparing style...
Loading networks from abstract_photo.pkl...
Traceback (most recent call last):
  File "E:\aimv2\main.py", line 7, in <module>
    L.hallucinate(file_name = 'E:\FFOutput\qby90.mp4')
  File "E:\aimv2\lucidsonicdreams\main.py", line 708, in hallucinate
    self.stylegan_init()
  File "E:\aimv2\lucidsonicdreams\main.py", line 179, in stylegan_init
    self.Gs = self.legacy.load_network_pkl(f)['G_ema'].to(device) # type: ignore
  File "E:\aimv2\stylegan2\legacy.py", line 26, in load_network_pkl
    G = convert_tf_generator(tf_G)
  File "E:\aimv2\stylegan2\legacy.py", line 111, in convert_tf_generator
    raise ValueError('TensorFlow pickle version too low')
ValueError: TensorFlow pickle version too low

Why???

**Comment by PDillis** [comment]
I know this is late, but this is because your model is a StyleGAN1, and the `convert_tf_generator` cannot convert between StyleGAN1 and StyleGAN2.

**Comment by bartman081523** [comment]
I had this error when I plugged in a stylegan2 config model trained with stylegan3
