### ISSUE TITLE
LSD on Replicate

### ISSUE THREAD

**Issue by voodoohop** [mikaelalafriz/lucid-sonic-dreams#44]
Hi,

I added Lucid Sonic Dreams to Replicate.com

https://replicate.com/pollinations/lucid-sonic-dreams

And with StyleGAN XL
https://replicate.com/pollinations/lucid-sonic-dreams-xl

You can also run them locally with cog. Check out the linked Github repositories if interested

**Comment by s852156** [comment]
how to upload video?

**Comment by s852156** [comment]
Hi, how to upload my own video and download as full HD size?

**Comment by s852156** [comment]
here's error...

Prediction failed.

'FullyConnectedLayer'

Traceback (most recent call last):
File "/root/.pyenv/versions/3.7.16/lib/python3.7/site-packages/cog/server/worker.py", line 217, in _predict
result = predict(**payload)
File "predict.py", line 201, in predict
G = legacy.load_network_pkl(f)['G_ema'].to(device) # type: ignore
File "/src/stylegan_xl/legacy.py", line 25, in load_network_pkl
data = _LegacyUnpickler(f).load()
File "/src/stylegan_xl/torch_utils/persistence.py", line 193, in _reconstruct_persistent_obj
orig_class = module.__dict__[meta.class_name]
KeyError: 'FullyConnectedLayer'
